$f = 'c:\Sim\src\App.tsx'
$c = [System.IO.File]::ReadAllText($f, [System.Text.Encoding]::UTF8)
$c = $c.Replace('Ã¶','ö')
$c = $c.Replace('Ã¥','å')
$c = $c.Replace('Ã¤','ä')
$c = $c.Replace('Ã–','Ö')
$c = $c.Replace('Ã…','Å')
$c = $c.Replace('Ã„','Ä')
$c = $c.Replace('Â°','°')
$c = $c.Replace('âˆ'','−')
$c = $c.Replace('â€"','—')
$c = $c.Replace('â˜…','★')
$c = $c.Replace('âœ•','✕')
$c = $c.Replace('âœ"','✓')
$c = $c.Replace('â–¸','▸')
$c = $c.Replace('â„','❄')
$c = $c.Replace('â™¦','♦')
$c = $c.Replace('ðŸ"‡','🔇')
$c = $c.Replace('ðŸ""','🔔')
[System.IO.File]::WriteAllText($f, $c, [System.Text.Encoding]::UTF8)
Write-Host "Done. Chars: $($c.Length)"
